### ISSUE TITLE
Images are too large (and include apt 's cache)

### ISSUE THREAD

**Issue by colemickens** [dotnet/dotnet-docker-preview#5]
I'd recommend clearing the apt cache in the same RUN invocation that you update it in. It ensures that you don't wind up making everyone download a copy of your apt cache.

example:
https://github.com/colemickens/polykube/blob/637b17dec481e8fba86d0628c13469efd019d485/dotnet/dockerfiles/dotnet-base/Dockerfile#L10

**Comment by friism** [comment]
Docs: https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#apt-get
